### ISSUE TITLE
Cannot install on Apple's new M1 chip

### ISSUE THREAD

**Issue by exalted** [aredridel/node-bin-gen#143]
Working with Apple's new laptops (M1 chip), and apparently, we're not able to install node as a dependency anymore:

Initialize:

```
$ npm --verbose init -y
npm verb cli [
npm verb cli   '/opt/homebrew/Cellar/node@16/16.13.0/libexec/node',
npm verb cli   '/opt/homebrew/Cellar/node@16/16.13.0/libexec/npm',
npm verb cli   '--verbose',
npm verb cli   'init',
npm verb cli   '-y'
npm verb cli ]
npm info using npm@8.1.0
npm info using node@v16.13.0
Wrote to /Users/user/myproject/package.json:

{
  "name": "myproject",
  "version": "1.0.0",
  "description": "myproject ====",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https:/github.com/exalted/myproject.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https:/github.com/exalted/myproject/issues"
  },
  "homepage": "https:/github.com/exalted/myproject#readme"
}


npm info init written successfully
npm verb exit 0
npm info ok
```

Install `npm` itself as a dependency using globally available `npm`:

```
$ npm --verbose install --save-exact npm@8.1.0
npm verb cli [
npm verb cli   '/opt/homebrew/Cellar/node@16/16.13.0/libexec/node',
npm verb cli   '/opt/homebrew/Cellar/node@16/16.13.0/libexec/npm',
npm verb cli   '--verbose',
npm verb cli   'install',
npm verb cli   '--save-exact',
npm verb cli   'npm@8.1.0'
npm verb cli ]
npm info using npm@8.1.0
npm info using node@v16.13.0
npm http fetch GET 200 https:/registry.npmjs.org/npm 9ms (cache hit)
npm http fetch GET 200 https:/registry.npmjs.org/npm/-/npm-8.1.0.tgz 2704ms (cache miss)

added 1 package in 3s

10 packages are looking for funding
  run `npm fund` for details
npm verb exit 0
npm info ok
```

Install `node` as a dependency using previously installed "local" `npm`:

```
$ ./node_modules/.bin/npm --verbose install --save-exact node@16.13.0
npm verb cli [
npm verb cli   '/opt/homebrew/Cellar/node@16/16.13.0/libexec/node',
npm verb cli   '/Users/user/myproject/node_modules/.bin/npm',
npm verb cli   '--verbose',
npm verb cli   'install',
npm verb cli   '--save-exact',
npm verb cli   'node@16.13.0'
npm verb cli ]
npm info using npm@8.1.0
npm info using node@v16.13.0
npm http fetch GET 200 https:/registry.npmjs.org/node 34ms (cache hit)
npm http fetch GET 200 https:/registry.npmjs.org/node-bin-setup 3ms (cache hit)
npm info run node@16.13.0 preinstall node_modules/node node installArchSpecificPackage
npm info run node@16.13.0 preinstall { code: 1, signal: null }
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/Users/user/myproject/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
npm verb stack     at ChildProcess.emit (node:events:390:28)
npm verb stack     at maybeClose (node:internal/child_process:1064:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm verb pkgid node@16.13.0
npm verb cwd /Users/user/myproject
npm verb Darwin 21.1.0
npm verb argv "/opt/homebrew/Cellar/node@16/16.13.0/libexec/node" "/Users/user/myproject/node_modules/.bin/npm" "--verbose" "install" "--save-exact" "node@16.13.0"
npm verb node v16.13.0
npm verb npm  v8.1.0
npm ERR! code 1
npm ERR! path /Users/user/myproject/node_modules/node
npm ERR! command failed
npm ERR! command sh -c node installArchSpecificPackage
npm ERR! npm verb cli [
npm ERR! npm verb cli   '/opt/homebrew/Cellar/node@16/16.13.0/libexec/node',
npm ERR! npm verb cli   '/opt/homebrew/Cellar/node@16/16.13.0/libexec/npm',
npm ERR! npm verb cli   'install',
npm ERR! npm verb cli   '--no-save',
npm ERR! npm verb cli   'node-darwin-arm64@16.13.0'
npm ERR! npm verb cli ]
npm ERR! npm info using npm@8.1.0
npm ERR! npm info using node@v16.13.0
npm ERR! npm http fetch GET 200 https:/registry.npmjs.org/node-bin-setup 6ms (cache hit)
npm ERR! npm http fetch GET 200 https:/registry.npmjs.org/node-darwin-arm64 2ms (cache hit)
npm ERR! npm verb type version
npm ERR! npm verb stack node-darwin-arm64: No matching version found for node-darwin-arm64@16.13.0.
npm ERR! npm verb stack     at module.exports (/opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm ERR! npm verb stack     at /opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm ERR! npm verb stack     at async Arborist.[nodeFromEdge] (/opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1061:19)
npm ERR! npm verb stack     at async Arborist.[buildDepStep] (/opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:11)
npm ERR! npm verb stack     at async Arborist.buildIdealTree (/opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
npm ERR! npm verb stack     at async Promise.all (index 1)
npm ERR! npm verb stack     at async Arborist.reify (/opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:149:5)
npm ERR! npm verb stack     at async Install.install (/opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/lib/install.js:170:5)
npm ERR! npm verb cwd /Users/user/myproject/node_modules/node
npm ERR! npm verb Darwin 21.1.0
npm ERR! npm verb argv "/opt/homebrew/Cellar/node@16/16.13.0/libexec/node" "/opt/homebrew/Cellar/node@16/16.13.0/libexec/npm" "install" "--no-save" "node-darwin-arm64@16.13.0"
npm ERR! npm verb node v16.13.0
npm ERR! npm verb npm  v8.1.0
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for node-darwin-arm64@16.13.0.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR! npm verb exit 1
npm ERR! npm verb unfinished npm timer reify 1638463503661
npm ERR! npm verb unfinished npm timer reify:loadTrees 1638463503665
npm ERR! npm verb code 1
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/user/.npm/_logs/2021-12-02T16_45_03_688Z-debug.log
npm ERR! node:internal/modules/cjs/loader:936
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'node-darwin-arm64/package.json'
npm ERR! Require stack:
npm ERR! - /Users/user/myproject/node_modules/node/installArchSpecificPackage.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
npm ERR!     at ChildProcess.<anonymous> (/Users/user/myproject/node_modules/node-bin-setup/index.js:18:27)
npm ERR!     at ChildProcess.emit (node:events:390:28)
npm ERR!     at maybeClose (node:internal/child_process:1064:16)
npm ERR!     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/Users/user/myproject/node_modules/node/installArchSpecificPackage.js'
npm ERR!   ]
npm ERR! }
npm verb exit 1
npm verb unfinished npm timer reify 1638463503311
npm verb unfinished npm timer reify:build 1638463503445
npm verb unfinished npm timer build 1638463503446
npm verb unfinished npm timer build:deps 1638463503446
npm verb unfinished npm timer build:run:preinstall 1638463503446
npm verb unfinished npm timer build:run:preinstall:node_modules/node 1638463503446
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2021-12-02T16_45_03_724Z-debug.log
```

Above-mentioned complete log file's contents:

```
0 verbose cli [
0 verbose cli   '/opt/homebrew/Cellar/node@16/16.13.0/libexec/node',
0 verbose cli   '/opt/homebrew/Cellar/node@16/16.13.0/libexec/npm',
0 verbose cli   'install',
0 verbose cli   '--no-save',
0 verbose cli   'node-darwin-arm64@16.13.0'
0 verbose cli ]
1 info using npm@8.1.0
2 info using node@v16.13.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/user/myproject/node_modules/node/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/Users/user/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/opt/homebrew/Cellar/node@16/16.13.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 5ms
19 timing npm:load:configload Completed in 5ms
20 timing npm:load:setTitle Completed in 2ms
21 timing npm:load:setupLog Completed in 0ms
22 timing config:load:flatten Completed in 1ms
23 timing npm:load:cleanupLog Completed in 1ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 0ms
26 timing npm:load Completed in 10ms
27 timing arborist:ctor Completed in 1ms
28 timing arborist:ctor Completed in 0ms
29 timing idealTree:init Completed in 6ms
30 timing idealTree:userRequests Completed in 2ms
31 silly idealTree buildDeps
32 silly fetch manifest node-bin-setup@^1.0.0
33 http fetch GET 200 https://registry.npmjs.org/node-bin-setup 6ms (cache hit)
34 silly fetch manifest node-darwin-arm64@16.13.0
35 http fetch GET 200 https://registry.npmjs.org/node-darwin-arm64 2ms (cache hit)
36 silly placeDep ROOT node-bin-setup@1.0.6 OK for: node@16.13.0 want: ^1.0.0
37 silly placeDep ROOT node-darwin-arm64@ OK for: node@16.13.0 want: 16.13.0
38 timing idealTree:#root Completed in 12ms
39 timing idealTree:node_modules/node-bin-setup Completed in 0ms
40 timing idealTree:node_modules/node-darwin-arm64 Completed in 0ms
41 timing idealTree:buildDeps Completed in 12ms
42 timing idealTree:fixDepFlags Completed in 0ms
43 timing idealTree Completed in 21ms
44 timing command:install Completed in 26ms
45 verbose type version
46 verbose stack node-darwin-arm64: No matching version found for node-darwin-arm64@16.13.0.
46 verbose stack     at module.exports (/opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
46 verbose stack     at /opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
46 verbose stack     at async Arborist.[nodeFromEdge] (/opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1061:19)
46 verbose stack     at async Arborist.[buildDepStep] (/opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:11)
46 verbose stack     at async Arborist.buildIdealTree (/opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
46 verbose stack     at async Promise.all (index 1)
46 verbose stack     at async Arborist.reify (/opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:149:5)
46 verbose stack     at async Install.install (/opt/homebrew/Cellar/node@16/16.13.0/lib/node_modules/npm/lib/install.js:170:5)
47 verbose cwd /Users/user/myproject/node_modules/node
48 verbose Darwin 21.1.0
49 verbose argv "/opt/homebrew/Cellar/node@16/16.13.0/libexec/node" "/opt/homebrew/Cellar/node@16/16.13.0/libexec/npm" "install" "--no-save" "node-darwin-arm64@16.13.0"
50 verbose node v16.13.0
51 verbose npm  v8.1.0
52 error code ETARGET
53 error notarget No matching version found for node-darwin-arm64@16.13.0.
54 error notarget In most cases you or one of your dependencies are requesting
54 error notarget a package version that doesn't exist.
55 verbose exit 1
```

**Comment by knpwrs** [comment]
I am likewise running into the same issue. The relevant portion of the log appears to be this:

```
npm ERR! Error: Cannot find module 'node-bin-darwin-arm64/package.json'
npm ERR! Require stack:
npm ERR! - /Users/knpwrs/Downloads/node_modules/node/installArchSpecificPackage.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
npm ERR!     at ChildProcess.<anonymous> (/Users/knpwrs/Downloads/node_modules/node-bin-setup/index.js:19:27)
npm ERR!     at ChildProcess.emit (node:events:390:28)
npm ERR!     at maybeClose (node:internal/child_process:1062:16)
npm ERR!     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/Users/knpwrs/Downloads/node_modules/node/installArchSpecificPackage.js'
npm ERR!   ]
npm ERR! }
```

**Comment by aredridel** [comment]
Ugh. A bug in https://github.com/aredridel/node-bin-setup — I'll look into it.

**Comment by aredridel** [comment]
Try now: I just pushed an update to node-bin-setup that should fix it.

**Comment by straub** [comment]
I'm still getting
```
npm ERR! Error: Cannot find module 'node-darwin-arm64/package.json'
```
for `npm i node@16.17.1`, `npm i node@16.13.2`, and `npm i node@18` on my M1, but haven't totally convinced myself it's not my fault somehow yet :P

**Comment by aredridel** [comment]
It should be `node-bin-darwin-arm64`; however this required an update to `node-bin-setup`, so if that's still cached or at version 1.0.0, that'd be the cause. Update that and it should work.

**Comment by straub** [comment]
Thanks, that did the trick! I ran `npm update node-bin-setup` and now all of `npm i node@16.17.1`, `npm i node@16.13.2`, and `npm i node@18` work like a charm :)
